language: swift
os: osx
osx_image: xcode11.3
env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8
    - PROJECT=SwiftErrorHandler.xcodeproj
    - SCHEME=SwiftErrorHandler-Package
    - EXPANDED_CODE_SIGN_IDENTITY=""
    - EXPANDED_CODE_SIGN_IDENTITY_NAME=""
    - EXPANDED_PROVISIONING_PROFILE=""
    - DESTINATION="platform=iOS Simulator,name=iPhone 11"
    - CC_TEST_REPORTER_ID=f9052cf7f98bd46742d8f3f5d140a053f8cfb4031046eb238d1e5de9b460ac6b
install:
  - git config --add diff.renamelimit 0

jobs:
  include:
    - stage: lint
      script:
        - swiftlint
        - pod lib lint
    - stage: test
      before_script:
        - gem install slather
        - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-darwin-amd64 > ./cc-test-reporter
        - chmod +x ./cc-test-reporter
        - ./cc-test-reporter before-build
      script:
        - set -o pipefail
        - xcodebuild -version
        - xcodebuild -showsdks
        - swift package generate-xcodeproj --xcconfig-overrides ./Sources/ios.xcconfig
        - xcodebuild -project "$PROJECT" -scheme "$SCHEME" -destination "$DESTINATION" -enableCodeCoverage YES clean build test | xcpretty
      after_script:
        - slather
        - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
    - stage: deploy
      if: tag IS present
      script:
        - swift package generate-xcodeproj --xcconfig-overrides ./Sources/ios.xcconfig
        - carthage version
        - carthage build --no-skip-current
        - carthage archive SwiftErrorHandler
      deploy:
        - provider: releases
          api_key:
            secure: lYOBEL27WJ8OG8L+IFXLZFrYYAxdPReq6NS1p8nwZs7O6Oc+namqbEp31fBl5XJLpCiq33DiCHLAQHEK7UTavGuvINADgPRlRn45Ieyd+CF8EAVsbK1cYS6+bXXt6RLcrBOS9wrGbpFt18HE1QdVrPtOztRjSvaCf+jMiS4jv1R8HOmWsy4Lxf6UtpPhcpwNqQ4aBt2C61Uwbt406pqVoxIZj/berN2i495LO52/S2eu+4E8wjoeaJSQKZgmMFNoZMpbwIrZIC0ShXRGTjyV/TuY2BSJucCXtxXtsxwF+JgGW+a8UyeMxltLv19DWyfMi2p+xttkZM7LgIFXPEj0+3DZeCwa3rHw/EWuqzXUsnBddZEyh6J9pc4i5ZlVI+uBmbbc0KxZsdSncRl6XL5cr3IHdlDCskqHSEYmW56qnhCqyGSyOZfn1QzM/1SsQIDQZ0S++VoHUEKrD+hhgY9ss7Ecc+cwEITGOGiLuLy6JEJtERTR5c0ovc6Sp/134sYHSeyX3OBvCBnoAPLqfdLtPX35Z5kSjSFuCLNnFY4oVDo1Ye57ypMUICu13WE2iiBPhUmQsJrJnWsy6aqes2OqFFM0tbMi8zu11EOQNSWIGWVWhW8On+7gnIiTiS8+vwAUM++dO/bcLFWZ2ixwt4djuF5lSl6Fh6UK1ow6JSjQFio=
          file: SwiftErrorHandler.framework.zip
          on:
            tags: true
        - provider: script
          script:
            - pod trunk push --allow-warnings
          on:
            tags: true
